AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation SES Providers
Parameters:
  LambdaImageUri:
    Type: String
    Default: ''
Outputs:
  CFNSESProviderArn:
    Description: The ServiceToken for the CFNSESProvider lambda.
    Value: !GetAtt CFNSESProvider.Arn
Resources:
  LambdaPolicy:
    Type: AWS::IAM::Policy
    DependsOn:
      - LambdaRole
    Properties:
      PolicyName: CFNSESProviderPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource: '*'
          - Effect: Allow
            Action:
              - route53:GetHostedZone
              - route53:ChangeResourceRecordSets
              - route53:ListResourceRecordSets
            Resource: '*'
          - Effect: Allow
            Action:
              - ses:VerifyDomainDkim
              - ses:DeleteIdentity
              - ses:ListIdentities
              - ses:VerifyDomainIdentity
              - ses:DescribeActiveReceiptRuleSet
              - ses:SetActiveReceiptRuleSet
              - ses:GetIdentityVerificationAttributes
              - ses:GetIdentityNotificationAttributes
              - ses:SetIdentityNotificationTopic
              - ses:SetIdentityHeadersInNotificationsEnabled
              - ses:SetIdentityFeedbackForwardingEnabled
              - ses:SetIdentityMailFromDomain
              - ses:ListIdentityPolicies
              - ses:GetIdentityPolicies
              - ses:PutIdentityPolicy
              - ses:DeleteIdentityPolicy
            Resource: '*'
          - Effect: Allow
            Action:
              - logs:*
            Resource: arn:aws:logs:*:*:*
      Roles:
        - !Ref 'LambdaRole'
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
  CFNSESProvider:
    Type: AWS::Lambda::Function
    DependsOn:
      - LambdaRole
      - LambdaPolicy
    Properties:
      Description: CloudFormation SES provider implementation
      Code:
        ImageUri: !Ref 'LambdaImageUri'
      MemorySize: 128
      Role: !GetAtt 'LambdaRole.Arn'
      Timeout: 30
      PackageType: Image
